### ISSUE TITLE
Missing gpiochip_find() when compiling on newer kernels

### ISSUE THREAD

**Issue by lucky62** [arthur-liberman/linux_openvfd#24]
I am trying to compile on armbian 6.7.4-edge-rockchip64:

linux_openvfd/driver/openvfd_drv.c:635:24: error: implicit declaration of function ‘gpiochip_find’; did you mean ‘gpiochip_add’? [-Werror=implicit-function-declaration]
  635 |                 chip = gpiochip_find((char *)bank_name, is_right_chip);

![image](https://github.com/arthur-liberman/linux_openvfd/assets/16965519/6c8fa94d-4cb4-433a-b49d-6aafa26872d5)

Seems function was removed.
How to solve?

**Comment by arthur-liberman** [comment]
@lucky62 I don't have any devices that use the v6.7 kernel.
Looks like `gpiochip_find` was deprecated and quickly replaced by `gpio_device_find`. But this is a different  method, and requires some extra code to get the `gpio_chip` object from it.
You can see how this transition was handled in the linux kernel code:
https://elixir.bootlin.com/linux/v6.6.26/source/drivers/gpio/gpiolib.c#L1022

**Comment by arthur-liberman** [comment]
Something like this patch:
```diff
diff --git a/driver/openvfd_drv.c b/driver/openvfd_drv.c
index 7766740..f20f8d3 100644
--- a/driver/openvfd_drv.c
+++ b/driver/openvfd_drv.c
@@ -617,6 +617,24 @@ static int is_right_chip(struct gpio_chip *chip, void *data)
        return 0;
 }
 
+#if LINUX_VERSION_CODE >= KERNEL_VERSION(6,7,0)
+static struct gpio_chip *gpiochip_find(void *data,
+                               int (*match)(struct gpio_chip *gc,
+                                            void *data))
+{
+       struct gpio_device *gdev;
+       struct gpio_chip *gc = NULL;
+
+       gdev = gpio_device_find(data, match);
+       if (gdev) {
+               gc = gdev->chip;
+               gpio_device_put(gdev);
+       }
+
+       return gc;
+}
+#endif
+
 static int get_chip_pin_number(const unsigned int gpio[])
 {
        int pin = -1;
```

**Comment by augin** [comment]
> Что-то вроде этого патча:
> 
> ```diff
> diff --git a/driver/openvfd_drv.c b/driver/openvfd_drv.c
> index 7766740..f20f8d3 100644
> --- a/driver/openvfd_drv.c
> +++ b/driver/openvfd_drv.c
> @@ -617,6 +617,24 @@ static int is_right_chip(struct gpio_chip *chip, void *data)
>         return 0;
>  }
>  
> +#if LINUX_VERSION_CODE >= KERNEL_VERSION(6,7,0)
> +static struct gpio_chip *gpiochip_find(void *data,
> +                               int (*match)(struct gpio_chip *gc,
> +                                            void *data))
> +{
> +       struct gpio_device *gdev;
> +       struct gpio_chip *gc = NULL;
> +
> +       gdev = gpio_device_find(data, match);
> +       if (gdev) {
> +               gc = gdev->chip;
> +               gpio_device_put(gdev);
> +       }
> +
> +       return gc;
> +}
> +#endif
> +
>  static int get_chip_pin_number(const unsigned int gpio[])
>  {
>         int pin = -1;
> ```
> 
> Пожалуйста, дайте мне знать, если это работает, я объединю это как исправление.

![image](https://github.com/arthur-liberman/linux_openvfd/assets/389674/bc14fca9-1eb2-4e9e-86b6-3c3f09699182)

**Comment by augin** [comment]
I add https://elixir.bootlin.com/linux/v6.7.4/source/drivers/gpio/gpiolib.h and include this. Its work!

**Comment by arthur-liberman** [comment]
Did you add it in addition to my proposed change or only that line?

**Comment by augin** [comment]
created PR

**Comment by KuroNeko-san** [comment]
Same error. Waiting for accepting that PR.

**Comment by KuroNeko-san** [comment]
Is there anything I can do to help? For example, provide SSH access to TV-box with 6.7.4 kernel for online testing?

**Comment by augin** [comment]
Just build from https://github.com/augin/linux_openvfd :)

**Comment by augin** [comment]
@arthur-liberman Thanks for your work!

**Comment by bigrob3rto** [comment]
> I add https://elixir.bootlin.com/linux/v6.7.4/source/drivers/gpio/gpiolib.h and include this. Its work!

same, i have kernel 6.8.11 on armbian, solved by adding to linux headers folder:
https://elixir.bootlin.com/linux/v6.8.11/source/drivers/gpio/gpiolib.h

and add new header in openvfd_drv.c
`#include <linux/gpiolib.h>`

**Comment by bigrob3rto** [comment]
2 problems on kernel 6.11.0

`/home/ror/linux_openvfd/driver/openvfd_drv.c:629:35: error: passing argument 2 of ‘gpio_device_find’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  629 |     gdev = gpio_device_find(data, match);
      |                                   ^~~~~
      |                                   |
      |                                   int (*)(struct gpio_chip *, void *)`

`/home/ror/linux_openvfd/driver/openvfd_drv.c:1034:19: error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Werror=incompatible-pointer-types]
 1034 |         .remove = openvfd_driver_remove,`

 build from https://github.com/augin/linux_openvfd
 
 No solution yet
